---
- name: Convert
  hosts: Centos_hosts
  strategy: free
  become: true
  force_handlers: true
  vars:
    rhsm_username:
    rhsm_password:
    rhsm_org:
    rhsm_activation_key:

  tasks:
    - name: Perform OS conversion
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert
...
